// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Fu5-JAGx6PAEsy85hbFSV0oEt7AoOS0',
    appId: '1:295785386901:web:9cba5144782dd5ee25dc9c',
    messagingSenderId: '295785386901',
    projectId: 'chat-app-f24a2',
    authDomain: 'chat-app-f24a2.firebaseapp.com',
    storageBucket: 'chat-app-f24a2.appspot.com',
    measurementId: 'G-2GF1ZHL8GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXiO_LyG6l7AKILfusmEBpE9kNMxveAY',
    appId: '1:295785386901:android:6d596268f218450425dc9c',
    messagingSenderId: '295785386901',
    projectId: 'chat-app-f24a2',
    storageBucket: 'chat-app-f24a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaYKrI345OoiJm9tgV7sp64QUnyE6WIeo',
    appId: '1:295785386901:ios:d08041e21fe0045a25dc9c',
    messagingSenderId: '295785386901',
    projectId: 'chat-app-f24a2',
    storageBucket: 'chat-app-f24a2.appspot.com',
    iosClientId: '295785386901-h3sd02l2pobcr99j43mb21fe7qua9ght.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaYKrI345OoiJm9tgV7sp64QUnyE6WIeo',
    appId: '1:295785386901:ios:3f7e5e184f31bc4625dc9c',
    messagingSenderId: '295785386901',
    projectId: 'chat-app-f24a2',
    storageBucket: 'chat-app-f24a2.appspot.com',
    iosClientId: '295785386901-d43svbkafi3t89vkr92ihih6cu826ml8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
